# Generated by Django 4.1.7 on 2023-04-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('songname', models.CharField(max_length=150)),
                ('songimage', models.ImageField(upload_to='image')),
                ('songaudio', models.FileField(upload_to='audio')),
                ('singer', models.CharField(max_length=2000)),
                ('songmoviename', models.CharField(default='None', max_length=150)),
                ('duration', models.IntegerField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
